modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="mobs_blocker"
version="1.1.0"
displayName="Mobs Blocker"
displayURL="https://modrinth.com/mod/mobsblocker"
logoFile="logo.png"
credits="Made with MCreaHub Optimized for high-performance servers."
authors="Dreyka Oas"
description="A simple tool to block any mob from spawning on your server. "
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mobs_blocker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration