modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="mobs_blocker"
version="1.0.0"
displayName="Mobs Blocker"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.mobs_blocker]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.251,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mobs_blocker]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration