modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="mobs_blocker"
version="1.2.0"
displayName="Mobs Blocker"
displayURL="https://modrinth.com/mod/mobsblocker"
logoFile="logo.png"
credits="Made with MCreaHub Optimized for high-performance servers."
authors="Dreyka Oas"
description="A simple tool to block any mob from spawning on your server. "
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.mobs_blocker]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.155,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mobs_blocker]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration